############################################################
# 03_curate_active_TB_signature_suppressor_candidates.R
# Curate and rank candidate compounds suppressing active-TB signature
############################################################

# -----------------------------
# 1. Load packages
# -----------------------------

packages <- c(
  "dplyr", "readr", "stringr", "tidyr",
  "ggplot2", "forcats", "scales", "openxlsx"
)

for (pkg in packages) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg)
  }
  library(pkg, character.only = TRUE)
}

# -----------------------------
# 2. Project directory
# -----------------------------

project_dir <- "C:/Users/acer/OneDrive/Desktop/Imran_MTB_DRUG-MODULATION"

out_dir <- file.path(project_dir, "results", "candidate_curation")
table_dir <- file.path(out_dir, "tables")
fig_dir <- file.path(out_dir, "figures")
log_dir <- file.path(out_dir, "logs")

dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(table_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(fig_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(log_dir, recursive = TRUE, showWarnings = FALSE)

cat("Project directory:\n")
cat(project_dir, "\n\n")

# -----------------------------
# 3. Find input files automatically
# -----------------------------

find_file_recursive <- function(project_dir, file_pattern, required = TRUE) {
  
  matched <- list.files(
    project_dir,
    pattern = file_pattern,
    recursive = TRUE,
    full.names = TRUE
  )
  
  # Avoid picking files generated by this script during reruns
  matched <- matched[!grepl("candidate_curation", matched)]
  
  if (length(matched) == 0 && required) {
    stop(paste("File not found:", file_pattern))
  }
  
  if (length(matched) == 0 && !required) {
    return(NA_character_)
  }
  
  return(matched[1])
}

active_file <- find_file_recursive(
  project_dir,
  "active_TB_up_matching_drug_DOWN_signatures\\.csv$",
  required = TRUE
)

anchor_file <- find_file_recursive(
  project_dir,
  "anchor_STAT1_GBP1\\.txt$",
  required = FALSE
)

core8_file <- find_file_recursive(
  project_dir,
  "core8_host_response_module\\.txt$",
  required = FALSE
)

cat("Using active-TB suppressor file:\n")
cat(active_file, "\n\n")

# -----------------------------
# 4. Load anchor/core genes
# -----------------------------

if (!is.na(anchor_file)) {
  anchor_genes <- readLines(anchor_file, warn = FALSE)
  anchor_genes <- toupper(trimws(anchor_genes))
  anchor_genes <- anchor_genes[anchor_genes != ""]
} else {
  anchor_genes <- c("STAT1", "GBP1")
}

if (!is.na(core8_file)) {
  core8_genes <- readLines(core8_file, warn = FALSE)
  core8_genes <- toupper(trimws(core8_genes))
  core8_genes <- core8_genes[core8_genes != ""]
} else {
  core8_genes <- c(
    "STAT1", "GBP1", "IFIT3", "IFI35",
    "IRF7", "PARP9", "IFIT2", "IFI6"
  )
}

cat("Anchor genes:\n")
print(anchor_genes)

cat("\nCore module genes:\n")
print(core8_genes)

# -----------------------------
# 5. Helper functions
# -----------------------------

find_first_col <- function(df, candidates) {
  hit <- candidates[candidates %in% names(df)]
  if (length(hit) == 0) return(NA_character_)
  hit[1]
}

clean_library_name <- function(x) {
  dplyr::case_when(
    x == "Drug_Perturbations_from_GEO_down" ~ "GEO drug perturbations (down)",
    x == "Drug_Perturbations_from_GEO_up" ~ "GEO drug perturbations (up)",
    x == "DSigDB" ~ "DSigDB",
    x == "LINCS_L1000_Chem_Pert_down" ~ "LINCS L1000 chemical perturbations (down)",
    x == "LINCS_L1000_Chem_Pert_up" ~ "LINCS L1000 chemical perturbations (up)",
    TRUE ~ x
  )
}

clean_term_name <- function(x) {
  x %>%
    str_replace_all("_", " ") %>%
    str_replace_all("&circ;", "^") %>%
    str_replace_all("&sup2;", "2") %>%
    str_replace_all("&alpha;", "alpha") %>%
    str_replace_all("&beta;", "beta") %>%
    str_replace_all("&gamma;", "gamma") %>%
    str_replace_all("&ndash;", "-") %>%
    str_replace_all("&mdash;", "-") %>%
    str_replace_all("\\s+", " ") %>%
    str_trim()
}

standardize_input <- function(df) {
  
  term_col <- find_first_col(df, c("Term", "term", "Description", "Geneset", "Gene_set"))
  
  adj_col <- find_first_col(df, c(
    "Adjusted_P_value", "Adjusted.P.value", "Adjusted P-value",
    "adjusted_p_value", "adj.P.Val", "P.adjust", "padj"
  ))
  
  lib_col <- find_first_col(df, c("Library", "library", "Gene_set_library", "GeneSetLibrary"))
  
  overlap_col <- find_first_col(df, c("Overlapping_genes", "Overlap", "overlap"))
  
  combined_col <- find_first_col(df, c(
    "Combined_score", "Combined.Score", "Combined Score", "combined_score"
  ))
  
  pval_col <- find_first_col(df, c("P_value", "P.value", "P-value", "P_Value", "p_value"))
  
  rank_col <- find_first_col(df, c("Rank", "rank"))
  
  if (is.na(term_col) || is.na(adj_col)) {
    stop("Required columns missing. Need at least Term and adjusted p-value.")
  }
  
  out <- data.frame(
    Rank = if (!is.na(rank_col)) suppressWarnings(as.numeric(df[[rank_col]])) else NA_real_,
    Term = as.character(df[[term_col]]),
    Adjusted_P = suppressWarnings(as.numeric(df[[adj_col]])),
    Library = if (!is.na(lib_col)) as.character(df[[lib_col]]) else "Unknown",
    Overlapping_genes = if (!is.na(overlap_col)) as.character(df[[overlap_col]]) else NA_character_,
    Combined_Score = if (!is.na(combined_col)) suppressWarnings(as.numeric(df[[combined_col]])) else NA_real_,
    P_Value = if (!is.na(pval_col)) suppressWarnings(as.numeric(df[[pval_col]])) else NA_real_,
    stringsAsFactors = FALSE
  )
  
  out %>%
    filter(!is.na(Term), !is.na(Adjusted_P)) %>%
    mutate(
      Library_clean = clean_library_name(Library),
      Term_clean = clean_term_name(Term),
      MinusLog10AdjP = -log10(Adjusted_P)
    )
}

extract_candidate_name <- function(term) {
  
  x <- clean_term_name(term)
  x <- str_trim(x)
  
  x <- str_replace(x, "\\s+DB[0-9]+.*$", "")
  x <- str_replace(x, "\\s+GSE[0-9]+.*$", "")
  x <- str_replace(x, "\\s+GSM[0-9]+.*$", "")
  x <- str_replace(x, "\\s+sample\\s+[0-9]+.*$", "")
  x <- str_replace(x, "\\s+human\\s+GSE[0-9]+.*$", "")
  x <- str_replace(x, "\\s+mouse\\s+GSE[0-9]+.*$", "")
  x <- str_replace(x, "\\s+rat\\s+GSE[0-9]+.*$", "")
  x <- str_replace(x, "\\s+homo sapiens.*$", "")
  x <- str_replace(x, "\\s+mus musculus.*$", "")
  x <- str_replace(x, "\\s+rattus norvegicus.*$", "")
  x <- str_replace(x, "\\s+[0-9]{4,}.*$", "")
  x <- str_replace(x, "\\s+\\d+\\s*(um|µm|nm|mm|hr|h|hours).*$", "")
  x <- str_replace(x, "\\s+\\d+h.*$", "")
  x <- str_replace(x, "\\s+\\d+hr.*$", "")
  x <- str_replace_all(x, "\\s+", " ")
  x <- str_trim(x)
  x <- str_to_title(x)
  
  return(x)
}

get_overlap_genes <- function(x) {
  if (is.na(x) || x == "") return(character(0))
  
  genes <- unlist(str_split(x, ";|,|/|\\s+"))
  genes <- toupper(trimws(genes))
  genes <- genes[genes != ""]
  
  unique(genes)
}

count_overlap_genes <- function(x) {
  length(get_overlap_genes(x))
}

count_gene_hits <- function(overlap_text, gene_set) {
  genes <- get_overlap_genes(overlap_text)
  length(intersect(genes, gene_set))
}

list_gene_hits <- function(overlap_text, gene_set) {
  genes <- get_overlap_genes(overlap_text)
  hits <- intersect(genes, gene_set)
  
  if (length(hits) == 0) return("")
  
  paste(hits, collapse = ";")
}

classify_candidate <- function(candidate_name, term_clean) {
  
  x <- tolower(paste(candidate_name, term_clean))
  
  toxic_or_exposure <- c(
    "cigarette", "smoke", "nickel", "cadmium", "arsenic", "lead",
    "mercury", "hypochlorous", "nitric oxide", "radiation",
    "uv", "ultraviolet", "ozone", "diesel", "silica",
    "lipopolysaccharide", "lps", "endotoxin"
  )
  
  endogenous_or_metabolic <- c(
    "palmitic acid", "glucose", "atp", "cholesterol",
    "oleic acid", "stearic acid", "lactic acid", "pyruvate",
    "hydrogen peroxide", "h2o2"
  )
  
  unclear_signature <- c(
    "brd-", "brdk", "ljp", "trcn", "shrna", "sirna",
    "knockdown", "overexpression"
  )
  
  if (any(str_detect(x, toxic_or_exposure))) {
    return("Exposure_or_toxicant")
  }
  
  if (any(str_detect(x, endogenous_or_metabolic))) {
    return("Endogenous_or_metabolic")
  }
  
  if (any(str_detect(x, unclear_signature))) {
    return("Unmapped_or_genetic_signature")
  }
  
  if (str_detect(x, "interferon|etanercept|adalimumab|infliximab|rituximab|antibody|mab")) {
    return("Biologic_or_immunomodulator")
  }
  
  return("Candidate_drug_or_compound")
}

normalize_01 <- function(x) {
  x <- as.numeric(x)
  x[is.infinite(x)] <- NA
  
  if (all(is.na(x))) return(rep(0, length(x)))
  
  rng <- range(x, na.rm = TRUE)
  
  if (rng[1] == rng[2]) return(rep(1, length(x)))
  
  (x - rng[1]) / (rng[2] - rng[1])
}

save_plot_versions <- function(plot_obj, file_base, width = 12, height = 8) {
  
  ggsave(
    filename = paste0(file_base, ".png"),
    plot = plot_obj,
    width = width,
    height = height,
    dpi = 600,
    bg = "white"
  )
  
  ggsave(
    filename = paste0(file_base, ".pdf"),
    plot = plot_obj,
    width = width,
    height = height,
    bg = "white"
  )
  
  ggsave(
    filename = paste0(file_base, ".tiff"),
    plot = plot_obj,
    width = width,
    height = height,
    dpi = 600,
    compression = "lzw",
    bg = "white"
  )
}

# -----------------------------
# 6. Read active-TB suppressor data
# -----------------------------

active_raw <- readr::read_csv(active_file, show_col_types = FALSE)

active_df <- standardize_input(active_raw)

active_df <- active_df %>%
  mutate(
    Candidate_Name = extract_candidate_name(Term_clean),
    Overlap_Count = sapply(Overlapping_genes, count_overlap_genes),
    Anchor_Hit_Count = sapply(Overlapping_genes, count_gene_hits, gene_set = anchor_genes),
    Core8_Hit_Count = sapply(Overlapping_genes, count_gene_hits, gene_set = core8_genes),
    Anchor_Hits = sapply(Overlapping_genes, list_gene_hits, gene_set = anchor_genes),
    Core8_Hits = sapply(Overlapping_genes, list_gene_hits, gene_set = core8_genes),
    Candidate_Class = mapply(classify_candidate, Candidate_Name, Term_clean)
  )

write_csv(
  active_df,
  file.path(table_dir, "01_active_TB_signature_suppressor_terms_cleaned.csv")
)

cat("Input suppressor terms:", nrow(active_df), "\n")

# -----------------------------
# 7. Candidate-level aggregation
# -----------------------------

candidate_summary <- active_df %>%
  group_by(Candidate_Name, Candidate_Class) %>%
  summarise(
    Supporting_Signatures = n(),
    Libraries = paste(sort(unique(Library_clean)), collapse = "; "),
    Library_Count = n_distinct(Library_clean),
    Best_Adjusted_P = min(Adjusted_P, na.rm = TRUE),
    Max_MinusLog10AdjP = max(MinusLog10AdjP, na.rm = TRUE),
    Mean_MinusLog10AdjP = mean(MinusLog10AdjP, na.rm = TRUE),
    Max_Combined_Score = max(Combined_Score, na.rm = TRUE),
    Mean_Combined_Score = mean(Combined_Score, na.rm = TRUE),
    Max_Overlap_Count = max(Overlap_Count, na.rm = TRUE),
    Total_Overlap_Count = sum(Overlap_Count, na.rm = TRUE),
    Max_Anchor_Hit_Count = max(Anchor_Hit_Count, na.rm = TRUE),
    Max_Core8_Hit_Count = max(Core8_Hit_Count, na.rm = TRUE),
    Anchor_Hits = paste(sort(unique(unlist(str_split(paste(Anchor_Hits, collapse = ";"), ";")))), collapse = ";"),
    Core8_Hits = paste(sort(unique(unlist(str_split(paste(Core8_Hits, collapse = ";"), ";")))), collapse = ";"),
    Top_Term = Term_clean[which.min(Adjusted_P)][1],
    .groups = "drop"
  ) %>%
  mutate(
    Anchor_Hits = str_replace_all(Anchor_Hits, "^;$|^NA$|NA;|;NA", ""),
    Core8_Hits = str_replace_all(Core8_Hits, "^;$|^NA$|NA;|;NA", ""),
    Max_Combined_Score = ifelse(is.infinite(Max_Combined_Score), NA, Max_Combined_Score),
    Mean_Combined_Score = ifelse(is.infinite(Mean_Combined_Score), NA, Mean_Combined_Score),
    Max_Overlap_Count = ifelse(is.infinite(Max_Overlap_Count), 0, Max_Overlap_Count),
    Total_Overlap_Count = ifelse(is.infinite(Total_Overlap_Count), 0, Total_Overlap_Count)
  )

# -----------------------------
# 8. Scoring system
# -----------------------------

candidate_summary <- candidate_summary %>%
  mutate(
    Score_Significance = normalize_01(Max_MinusLog10AdjP),
    Score_Combined = normalize_01(Max_Combined_Score),
    Score_Overlap = normalize_01(Max_Overlap_Count),
    Score_Reproducibility = normalize_01(Supporting_Signatures),
    Score_Library = normalize_01(Library_Count),
    Score_Anchor = ifelse(Max_Anchor_Hit_Count > 0, 1, 0),
    Score_Core8 = normalize_01(Max_Core8_Hit_Count),
    
    Raw_Priority_Score =
      0.25 * Score_Combined +
      0.25 * Score_Significance +
      0.15 * Score_Overlap +
      0.15 * Score_Reproducibility +
      0.10 * Score_Core8 +
      0.05 * Score_Anchor +
      0.05 * Score_Library,
    
    Priority_Score_100 = round(100 * Raw_Priority_Score, 2)
  ) %>%
  arrange(desc(Priority_Score_100), Best_Adjusted_P)

# -----------------------------
# 9. Separate candidate categories
# -----------------------------

ranked_all <- candidate_summary

ranked_candidate_drugs <- ranked_all %>%
  filter(Candidate_Class %in% c("Candidate_drug_or_compound", "Biologic_or_immunomodulator")) %>%
  arrange(desc(Priority_Score_100), Best_Adjusted_P)

removed_or_flagged_terms <- ranked_all %>%
  filter(!Candidate_Class %in% c("Candidate_drug_or_compound", "Biologic_or_immunomodulator")) %>%
  arrange(desc(Priority_Score_100), Best_Adjusted_P)

write_csv(
  ranked_all,
  file.path(table_dir, "02_ranked_all_active_TB_signature_suppressor_candidates.csv")
)

write_csv(
  ranked_candidate_drugs,
  file.path(table_dir, "03_ranked_candidate_drugs_active_TB_signature_suppressors.csv")
)

write_csv(
  removed_or_flagged_terms,
  file.path(table_dir, "04_flagged_non_drug_or_unclear_terms.csv")
)

cat("\nRanked all candidates:", nrow(ranked_all), "\n")
cat("Ranked candidate drugs/biologics:", nrow(ranked_candidate_drugs), "\n")
cat("Flagged non-drug/unclear terms:", nrow(removed_or_flagged_terms), "\n")

# -----------------------------
# 10. Top candidate summary
# -----------------------------

top20_candidates <- ranked_candidate_drugs %>%
  select(
    Candidate_Name,
    Candidate_Class,
    Priority_Score_100,
    Supporting_Signatures,
    Library_Count,
    Best_Adjusted_P,
    Max_Combined_Score,
    Max_Overlap_Count,
    Max_Anchor_Hit_Count,
    Max_Core8_Hit_Count,
    Anchor_Hits,
    Core8_Hits,
    Libraries,
    Top_Term
  ) %>%
  head(20)

write_csv(
  top20_candidates,
  file.path(table_dir, "05_TOP20_ranked_active_TB_signature_suppressor_candidates.csv")
)

# -----------------------------
# 11. Candidate class summary
# -----------------------------

class_summary <- ranked_all %>%
  count(Candidate_Class, name = "Candidate_Count") %>%
  arrange(desc(Candidate_Count))

write_csv(
  class_summary,
  file.path(table_dir, "06_candidate_class_summary.csv")
)

# -----------------------------
# 12. Figures
# -----------------------------

p_class <- ggplot(
  class_summary,
  aes(x = fct_reorder(Candidate_Class, Candidate_Count), y = Candidate_Count)
) +
  geom_col(fill = "#4B8BBE", color = "black", linewidth = 0.35, width = 0.7) +
  geom_text(aes(label = Candidate_Count), hjust = -0.1, size = 6, fontface = "bold") +
  coord_flip() +
  scale_y_continuous(expand = expansion(mult = c(0, 0.18))) +
  labs(
    title = "Candidate category distribution",
    x = NULL,
    y = "Number of candidates"
  ) +
  theme_bw(base_size = 20) +
  theme(
    plot.title = element_text(size = 25, face = "bold", hjust = 0.5),
    axis.title.x = element_text(size = 22, face = "bold"),
    axis.text.x = element_text(size = 18, face = "bold"),
    axis.text.y = element_text(size = 18, face = "bold"),
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(),
    plot.margin = margin(15, 35, 15, 15)
  )

save_plot_versions(
  p_class,
  file.path(fig_dir, "Figure_1_candidate_category_distribution"),
  width = 11,
  height = 7
)

top20_plot <- top20_candidates %>%
  mutate(
    Candidate_Label = str_wrap(Candidate_Name, width = 35),
    Candidate_Label = fct_reorder(Candidate_Label, Priority_Score_100)
  )

p_top20 <- ggplot(
  top20_plot,
  aes(x = Candidate_Label, y = Priority_Score_100)
) +
  geom_col(fill = "#E95A4F", color = "black", linewidth = 0.35, width = 0.7) +
  geom_text(aes(label = Priority_Score_100), hjust = -0.08, size = 5.5, fontface = "bold") +
  coord_flip() +
  scale_y_continuous(expand = expansion(mult = c(0, 0.18))) +
  labs(
    title = "Top active-TB signature suppressor candidates",
    x = NULL,
    y = "Priority score"
  ) +
  theme_bw(base_size = 20) +
  theme(
    plot.title = element_text(size = 25, face = "bold", hjust = 0.5),
    axis.title.x = element_text(size = 22, face = "bold"),
    axis.text.x = element_text(size = 17, face = "bold"),
    axis.text.y = element_text(size = 17, face = "bold"),
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(),
    plot.margin = margin(15, 40, 15, 15)
  )

save_plot_versions(
  p_top20,
  file.path(fig_dir, "Figure_2_top20_active_TB_signature_suppressor_candidates"),
  width = 12,
  height = 10
)

top15_components <- ranked_candidate_drugs %>%
  head(15) %>%
  select(
    Candidate_Name,
    Score_Combined,
    Score_Significance,
    Score_Overlap,
    Score_Reproducibility,
    Score_Core8,
    Score_Anchor,
    Score_Library
  ) %>%
  pivot_longer(
    cols = starts_with("Score_"),
    names_to = "Score_Component",
    values_to = "Score_Value"
  ) %>%
  mutate(
    Candidate_Label = str_wrap(Candidate_Name, width = 25),
    Score_Component = recode(
      Score_Component,
      "Score_Combined" = "Combined score",
      "Score_Significance" = "Significance",
      "Score_Overlap" = "Gene overlap",
      "Score_Reproducibility" = "Repeated evidence",
      "Score_Core8" = "Core module",
      "Score_Anchor" = "STAT1/GBP1",
      "Score_Library" = "Library support"
    )
  )

p_components <- ggplot(
  top15_components,
  aes(x = Score_Component, y = Candidate_Label, fill = Score_Value)
) +
  geom_tile(color = "white", linewidth = 0.45) +
  scale_fill_gradient(low = "white", high = "#2C7FB8", limits = c(0, 1)) +
  labs(
    title = "Evidence components supporting top candidates",
    x = NULL,
    y = NULL,
    fill = "Scaled\nscore"
  ) +
  theme_bw(base_size = 18) +
  theme(
    plot.title = element_text(size = 24, face = "bold", hjust = 0.5),
    axis.text.x = element_text(size = 15, face = "bold", angle = 45, hjust = 1),
    axis.text.y = element_text(size = 15, face = "bold"),
    legend.title = element_text(size = 15, face = "bold"),
    legend.text = element_text(size = 14),
    panel.grid = element_blank(),
    plot.margin = margin(15, 25, 15, 15)
  )

save_plot_versions(
  p_components,
  file.path(fig_dir, "Figure_3_top15_candidate_evidence_components"),
  width = 12,
  height = 8.5
)

# -----------------------------
# 13. Save Excel workbook
# -----------------------------

xlsx_file <- file.path(out_dir, "active_TB_signature_suppressor_candidate_curation.xlsx")

wb <- createWorkbook()

addWorksheet(wb, "Cleaned_terms")
writeData(wb, "Cleaned_terms", active_df)

addWorksheet(wb, "Ranked_all")
writeData(wb, "Ranked_all", ranked_all)

addWorksheet(wb, "Ranked_candidates")
writeData(wb, "Ranked_candidates", ranked_candidate_drugs)

addWorksheet(wb, "Flagged_terms")
writeData(wb, "Flagged_terms", removed_or_flagged_terms)

addWorksheet(wb, "Top20_candidates")
writeData(wb, "Top20_candidates", top20_candidates)

addWorksheet(wb, "Class_summary")
writeData(wb, "Class_summary", class_summary)

saveWorkbook(wb, xlsx_file, overwrite = TRUE)

cat("\nExcel workbook saved:\n")
cat(xlsx_file, "\n")

# -----------------------------
# 14. Save scoring note
# -----------------------------

scoring_note <- data.frame(
  Component = c(
    "Score_Combined",
    "Score_Significance",
    "Score_Overlap",
    "Score_Reproducibility",
    "Score_Core8",
    "Score_Anchor",
    "Score_Library"
  ),
  Weight = c(0.25, 0.25, 0.15, 0.15, 0.10, 0.05, 0.05),
  Meaning = c(
    "Maximum Enrichr combined score",
    "Strength of adjusted p-value",
    "Maximum number of overlapping active-TB genes",
    "Number of repeated supporting signatures",
    "Overlap with 8-gene host-response module",
    "Overlap with STAT1/GBP1 anchor genes",
    "Number of supporting perturbation libraries"
  )
)

write_csv(
  scoring_note,
  file.path(log_dir, "candidate_priority_scoring_note.csv")
)

# -----------------------------
# 15. Save session info
# -----------------------------

sink(file.path(log_dir, "session_info_candidate_curation.txt"))
sessionInfo()
sink()

# -----------------------------
# 16. Final console output
# -----------------------------

cat("\nCandidate curation completed successfully.\n")
cat("Tables saved in:\n")
cat(table_dir, "\n\n")
cat("Figures saved in:\n")
cat(fig_dir, "\n\n")
cat("Top 20 candidates:\n")
print(top20_candidates)