# -*- coding: utf-8 -*-
"""Imran_mtb_drug_modulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OVWhw7t5FQPBufqw-KtylaIGG7vBERTx
"""

!pip install chembl_webresource_client pandas openpyxl tqdm -q

import pandas as pd
import numpy as np
from tqdm import tqdm
from chembl_webresource_client.new_client import new_client

targets_to_check = [
    "STAT1",
    "GBP1",
    "JAK1",
    "JAK2",
    "TYK2",
    "RIPK2",
    "HDAC2",
    "HDAC8",
    "VDR"
]

target_client = new_client.target

target_rows = []

for gene in targets_to_check:
    results = list(target_client.search(gene))

    for r in results:
        target_rows.append({
            "query_gene": gene,
            "target_chembl_id": r.get("target_chembl_id"),
            "pref_name": r.get("pref_name"),
            "organism": r.get("organism"),
            "target_type": r.get("target_type")
        })

target_df = pd.DataFrame(target_rows)

# Keep likely human single-protein targets
human_single = target_df[
    (target_df["organism"] == "Homo sapiens") &
    (target_df["target_type"] == "SINGLE PROTEIN")
].copy()

human_single

best_targets = (
    human_single
    .sort_values(["query_gene", "target_chembl_id"])
    .drop_duplicates(subset=["query_gene"], keep="first")
    .reset_index(drop=True)
)

best_targets

best_targets.to_csv("ChEMBL_target_mapping_selected.csv", index=False)

activity_client = new_client.activity

activity_types = ["IC50", "Ki", "Kd", "EC50"]
all_activity_rows = []

for _, row in tqdm(best_targets.iterrows(), total=len(best_targets)):
    gene = row["query_gene"]
    target_id = row["target_chembl_id"]
    target_name = row["pref_name"]

    try:
        activities = activity_client.filter(
            target_chembl_id=target_id,
            standard_type__in=activity_types,
            standard_units="nM"
        ).only(
            "molecule_chembl_id",
            "canonical_smiles",
            "standard_type",
            "standard_relation",
            "standard_value",
            "standard_units",
            "pchembl_value",
            "assay_type",
            "target_chembl_id",
            "document_chembl_id"
        )

        for a in activities:
            all_activity_rows.append({
                "query_gene": gene,
                "target_chembl_id": target_id,
                "target_name": target_name,
                "molecule_chembl_id": a.get("molecule_chembl_id"),
                "canonical_smiles": a.get("canonical_smiles"),
                "standard_type": a.get("standard_type"),
                "standard_relation": a.get("standard_relation"),
                "standard_value": a.get("standard_value"),
                "standard_units": a.get("standard_units"),
                "pchembl_value": a.get("pchembl_value"),
                "assay_type": a.get("assay_type"),
                "document_chembl_id": a.get("document_chembl_id")
            })

    except Exception as e:
        print(f"Failed for {gene} ({target_id}): {e}")

activity_df = pd.DataFrame(all_activity_rows)
activity_df.shape

if activity_df.empty:
    print("No activity records found.")
else:
    clean_activity = activity_df.copy()

    clean_activity["pchembl_value"] = pd.to_numeric(
        clean_activity["pchembl_value"],
        errors="coerce"
    )

    clean_activity["standard_value"] = pd.to_numeric(
        clean_activity["standard_value"],
        errors="coerce"
    )

    clean_activity = clean_activity.dropna(
        subset=["molecule_chembl_id", "canonical_smiles", "pchembl_value"]
    )

    # Prefer exact activity relation where available
    clean_activity_exact = clean_activity[
        clean_activity["standard_relation"].isin(["=", None, np.nan])
        | clean_activity["standard_relation"].isna()
    ].copy()

    print("Raw records:", len(activity_df))
    print("Clean records with pChEMBL:", len(clean_activity))
    print("Exact/usable relation records:", len(clean_activity_exact))

summary_rows = []

for gene in targets_to_check:
    sub = clean_activity[clean_activity["query_gene"] == gene].copy()

    if sub.empty:
        summary_rows.append({
            "gene": gene,
            "target_name": None,
            "target_chembl_id": None,
            "raw_records": 0,
            "clean_records": 0,
            "unique_compounds": 0,
            "activity_types": "",
            "QSAR_feasibility": "No data"
        })
        continue

    unique_compounds = sub["molecule_chembl_id"].nunique()
    raw_records = activity_df[activity_df["query_gene"] == gene].shape[0]

    if unique_compounds >= 300:
        feasibility = "Strong QSAR"
    elif unique_compounds >= 100:
        feasibility = "Acceptable QSAR"
    elif unique_compounds >= 50:
        feasibility = "Weak/Possible"
    else:
        feasibility = "Not enough"

    summary_rows.append({
        "gene": gene,
        "target_name": sub["target_name"].iloc[0],
        "target_chembl_id": sub["target_chembl_id"].iloc[0],
        "raw_records": raw_records,
        "clean_records": len(sub),
        "unique_compounds": unique_compounds,
        "activity_types": "; ".join(sorted(sub["standard_type"].dropna().unique())),
        "QSAR_feasibility": feasibility
    })

chembl_summary = pd.DataFrame(summary_rows)
chembl_summary.sort_values("unique_compounds", ascending=False)

output_excel = "ChEMBL_bioactivity_feasibility_STAT_GBP_JAK_regulators.xlsx"

with pd.ExcelWriter(output_excel, engine="openpyxl") as writer:
    target_df.to_excel(writer, sheet_name="All_target_search", index=False)
    human_single.to_excel(writer, sheet_name="Human_single_targets", index=False)
    best_targets.to_excel(writer, sheet_name="Selected_targets", index=False)
    activity_df.to_excel(writer, sheet_name="Raw_activities", index=False)
    clean_activity.to_excel(writer, sheet_name="Clean_activities", index=False)
    chembl_summary.to_excel(writer, sheet_name="Feasibility_summary", index=False)

activity_df.to_csv("ChEMBL_raw_activities.csv", index=False)
clean_activity.to_csv("ChEMBL_clean_activities.csv", index=False)
chembl_summary.to_csv("ChEMBL_feasibility_summary.csv", index=False)

print("Saved:", output_excel)
print("Saved CSV files.")

from google.colab import files

files.download(output_excel)
files.download("ChEMBL_feasibility_summary.csv")
files.download("ChEMBL_clean_activities.csv")

!pip install chembl_webresource_client pandas numpy openpyxl matplotlib tqdm -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
from chembl_webresource_client.new_client import new_client
from google.colab import files
import os

project_name = "JAK1_TYK2_QSAR_preparation"

os.makedirs(project_name, exist_ok=True)
os.makedirs(f"{project_name}/tables", exist_ok=True)
os.makedirs(f"{project_name}/figures", exist_ok=True)

print("Output folder:", project_name)

targets_to_prepare = ["JAK1", "TYK2"]

target_client = new_client.target

target_rows = []

for gene in targets_to_prepare:
    results = list(target_client.search(gene))

    for r in results:
        target_rows.append({
            "query_gene": gene,
            "target_chembl_id": r.get("target_chembl_id"),
            "pref_name": r.get("pref_name"),
            "organism": r.get("organism"),
            "target_type": r.get("target_type")
        })

target_search_df = pd.DataFrame(target_rows)

target_search_df.to_csv(
    f"{project_name}/tables/ChEMBL_target_search_JAK1_TYK2.csv",
    index=False
)

target_search_df

human_single = target_search_df[
    (target_search_df["organism"] == "Homo sapiens") &
    (target_search_df["target_type"] == "SINGLE PROTEIN")
].copy()

human_single

selected_targets = (
    human_single
    .sort_values(["query_gene", "target_chembl_id"])
    .drop_duplicates(subset=["query_gene"], keep="first")
    .reset_index(drop=True)
)

selected_targets.to_csv(
    f"{project_name}/tables/selected_ChEMBL_targets_JAK1_TYK2.csv",
    index=False
)

selected_targets

activity_client = new_client.activity

all_activity_rows = []

for _, row in tqdm(selected_targets.iterrows(), total=len(selected_targets)):

    gene = row["query_gene"]
    target_id = row["target_chembl_id"]
    target_name = row["pref_name"]

    activities = activity_client.filter(
        target_chembl_id=target_id,
        standard_type="IC50",
        standard_units="nM"
    ).only(
        "molecule_chembl_id",
        "canonical_smiles",
        "standard_type",
        "standard_relation",
        "standard_value",
        "standard_units",
        "pchembl_value",
        "assay_type",
        "assay_description",
        "target_chembl_id",
        "document_chembl_id"
    )

    for a in activities:
        all_activity_rows.append({
            "target_gene": gene,
            "target_chembl_id": target_id,
            "target_name": target_name,
            "molecule_chembl_id": a.get("molecule_chembl_id"),
            "canonical_smiles": a.get("canonical_smiles"),
            "standard_type": a.get("standard_type"),
            "standard_relation": a.get("standard_relation"),
            "standard_value_nM": a.get("standard_value"),
            "standard_units": a.get("standard_units"),
            "pchembl_value": a.get("pchembl_value"),
            "assay_type": a.get("assay_type"),
            "assay_description": a.get("assay_description"),
            "document_chembl_id": a.get("document_chembl_id")
        })

raw_activity = pd.DataFrame(all_activity_rows)

raw_activity.to_csv(
    f"{project_name}/tables/raw_ChEMBL_IC50_JAK1_TYK2.csv",
    index=False
)

print("Raw records:", raw_activity.shape)
raw_activity.head()

clean_activity = raw_activity.copy()

clean_activity["standard_value_nM"] = pd.to_numeric(
    clean_activity["standard_value_nM"],
    errors="coerce"
)

clean_activity["pchembl_value"] = pd.to_numeric(
    clean_activity["pchembl_value"],
    errors="coerce"
)

# Keep usable records
clean_activity = clean_activity.dropna(
    subset=["molecule_chembl_id", "canonical_smiles", "standard_value_nM", "pchembl_value"]
)

# Keep positive IC50 values only
clean_activity = clean_activity[clean_activity["standard_value_nM"] > 0].copy()

# Keep exact or missing relation only
clean_activity = clean_activity[
    (clean_activity["standard_relation"].isna()) |
    (clean_activity["standard_relation"] == "=")
].copy()

# Remove duplicate exact rows
clean_activity = clean_activity.drop_duplicates()

clean_activity.to_csv(
    f"{project_name}/tables/clean_IC50_records_before_deduplication.csv",
    index=False
)

print("Clean records before compound-level deduplication:", clean_activity.shape)
clean_activity.groupby("target_gene")["molecule_chembl_id"].nunique()

qsar_ready = (
    clean_activity
    .groupby(["target_gene", "target_chembl_id", "target_name", "molecule_chembl_id", "canonical_smiles"], as_index=False)
    .agg(
        median_pchembl=("pchembl_value", "median"),
        mean_pchembl=("pchembl_value", "mean"),
        sd_pchembl=("pchembl_value", "std"),
        min_pchembl=("pchembl_value", "min"),
        max_pchembl=("pchembl_value", "max"),
        median_IC50_nM=("standard_value_nM", "median"),
        n_records=("pchembl_value", "count"),
        n_documents=("document_chembl_id", pd.Series.nunique)
    )
)

qsar_ready["sd_pchembl"] = qsar_ready["sd_pchembl"].fillna(0)

# Add activity class for later classification if needed
qsar_ready["activity_class"] = np.where(
    qsar_ready["median_pchembl"] >= 6,
    "Active",
    "Less_active"
)

qsar_ready.to_csv(
    f"{project_name}/tables/QSAR_ready_JAK1_TYK2_combined.csv",
    index=False
)

print("QSAR-ready records:", qsar_ready.shape)
qsar_ready.groupby("target_gene")["molecule_chembl_id"].nunique()

for target in ["JAK1", "TYK2"]:
    sub = qsar_ready[qsar_ready["target_gene"] == target].copy()

    sub.to_csv(
        f"{project_name}/tables/QSAR_ready_{target}_IC50.csv",
        index=False
    )

    print(target, "QSAR compounds:", sub.shape[0])

summary_rows = []

for target in ["JAK1", "TYK2"]:

    raw_sub = raw_activity[raw_activity["target_gene"] == target]
    clean_sub = clean_activity[clean_activity["target_gene"] == target]
    qsar_sub = qsar_ready[qsar_ready["target_gene"] == target]

    n_qsar = qsar_sub["molecule_chembl_id"].nunique()

    if n_qsar >= 300:
        feasibility = "Strong QSAR"
    elif n_qsar >= 100:
        feasibility = "Acceptable QSAR"
    elif n_qsar >= 50:
        feasibility = "Weak/Possible"
    else:
        feasibility = "Not enough"

    summary_rows.append({
        "target_gene": target,
        "raw_records": raw_sub.shape[0],
        "clean_records": clean_sub.shape[0],
        "qsar_unique_compounds": n_qsar,
        "median_pchembl_min": qsar_sub["median_pchembl"].min(),
        "median_pchembl_max": qsar_sub["median_pchembl"].max(),
        "median_pchembl_mean": qsar_sub["median_pchembl"].mean(),
        "active_compounds_pchembl_ge_6": (qsar_sub["median_pchembl"] >= 6).sum(),
        "less_active_compounds_pchembl_lt_6": (qsar_sub["median_pchembl"] < 6).sum(),
        "QSAR_feasibility": feasibility
    })

feasibility_summary = pd.DataFrame(summary_rows)

feasibility_summary.to_csv(
    f"{project_name}/tables/JAK1_TYK2_QSAR_feasibility_summary.csv",
    index=False
)

feasibility_summary

for target in ["JAK1", "TYK2"]:

    sub = qsar_ready[qsar_ready["target_gene"] == target].copy()

    plt.figure(figsize=(6, 4))
    plt.hist(sub["median_pchembl"], bins=30)
    plt.xlabel("Median pChEMBL")
    plt.ylabel("Number of compounds")
    plt.title(f"{target} IC50 pChEMBL distribution")
    plt.tight_layout()

    plt.savefig(
        f"{project_name}/figures/{target}_pchembl_distribution.png",
        dpi=300
    )

    plt.savefig(
        f"{project_name}/figures/{target}_pchembl_distribution.pdf"
    )

    plt.show()

class_counts = (
    qsar_ready
    .groupby(["target_gene", "activity_class"])
    .size()
    .reset_index(name="count")
)

plt.figure(figsize=(6, 4))

for target in class_counts["target_gene"].unique():
    sub = class_counts[class_counts["target_gene"] == target]
    plt.bar(
        sub["target_gene"] + "_" + sub["activity_class"],
        sub["count"]
    )

plt.xticks(rotation=45, ha="right")
plt.ylabel("Number of compounds")
plt.title("Activity class distribution")
plt.tight_layout()

plt.savefig(
    f"{project_name}/figures/JAK1_TYK2_activity_class_distribution.png",
    dpi=300
)

plt.savefig(
    f"{project_name}/figures/JAK1_TYK2_activity_class_distribution.pdf"
)

plt.show()

excel_file = f"{project_name}/JAK1_TYK2_QSAR_dataset_preparation.xlsx"

with pd.ExcelWriter(excel_file, engine="openpyxl") as writer:
    target_search_df.to_excel(writer, sheet_name="Target_search", index=False)
    selected_targets.to_excel(writer, sheet_name="Selected_targets", index=False)
    raw_activity.to_excel(writer, sheet_name="Raw_IC50_records", index=False)
    clean_activity.to_excel(writer, sheet_name="Clean_IC50_records", index=False)
    qsar_ready.to_excel(writer, sheet_name="QSAR_ready_combined", index=False)
    feasibility_summary.to_excel(writer, sheet_name="Feasibility_summary", index=False)

print("Excel saved:", excel_file)

!zip -r JAK1_TYK2_QSAR_preparation_results.zip JAK1_TYK2_QSAR_preparation > /dev/null

files.download("JAK1_TYK2_QSAR_preparation_results.zip")
files.download(excel_file)
files.download(f"{project_name}/tables/JAK1_TYK2_QSAR_feasibility_summary.csv")

