# -*- coding: utf-8 -*-
"""Imran_JAK2_ZINC_Enamine_external_similarity_COLAB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oRCdT4xmcsCxUeMAqgF_QjLMgn4aTzfb

# JAK2 ZINC/Enamine external similarity screening
Upload seed file + ZINC/Enamine SMILES files, then run cells step by step.
"""

!pip -q install rdkit pandas numpy tqdm openpyxl matplotlib
from rdkit import Chem
print('RDKit test:', Chem.MolFromSmiles('CCO').GetNumAtoms())

"""## Upload files
Upload these files to Colab:
- `30_zinc_enamine_similarity_screening.py`
- `JAK2_seed_ligands_READY.csv`
- your ZINC file, e.g. `zinc_input.smi`
- your Enamine file, e.g. `enamine_input.smi`

"""

from google.colab import files
uploaded = files.upload()

# Edit file names here if your uploaded files have different names
ZINC_FILE = 'zinc_input.smi'
ENAMINE_FILE = 'enamine_input.smi'
SEED_FILE = 'JAK2_seed_ligands_READY.csv'
SCRIPT_FILE = '30_zinc_enamine_similarity_screening.py'

import os
for f in [SCRIPT_FILE, SEED_FILE, ZINC_FILE, ENAMINE_FILE]:
    print(f, 'FOUND' if os.path.exists(f) else 'MISSING')

!python 30_zinc_enamine_similarity_screening.py \
  --seeds JAK2_seed_ligands_READY.csv \
  --input zinc_input.smi enamine_input.smi \
  --outdir ZINC_Enamine_external_similarity \
  --top_n 1000 \
  --select_n 100 \
  --min_similarity 0.25 \
  --max_known_similarity 0.85

import os, glob

print("Current folder:", os.getcwd())

print("\nFiles in current folder:")
for f in sorted(glob.glob("*")):
    print(" -", f)

print("\nFolders:")
for f in sorted(glob.glob("*/")):
    print(" -", f)

print("\nExpected output folder exists?")
print(os.path.exists("ZINC_Enamine_external_similarity"))

if os.path.exists("ZINC_Enamine_external_similarity"):
    print("\nFiles inside output folder:")
    for f in sorted(glob.glob("ZINC_Enamine_external_similarity/*")):
        print(" -", f)

import pandas as pd
import os

for file in ["zinc_enamine_library_TEMPLATE.csv", "zinc_enamine_library_TEMPLATE (1).csv"]:
    if os.path.exists(file):
        print("\nFILE:", file)
        df = pd.read_csv(file)
        print("Shape:", df.shape)
        print("Columns:", list(df.columns))
        display(df.head(10))

import pandas as pd, os, glob

print("Files:")
for f in glob.glob("*"):
    print(f)

for file in ["zinc_input.smi", "enamine_input.smi"]:
    if os.path.exists(file):
        print("\nChecking:", file)
        with open(file, "r", encoding="utf-8", errors="ignore") as fh:
            for i in range(5):
                print(fh.readline().strip())
    else:
        print("\nNot found:", file)

import pandas as pd
selected = pd.read_csv('ZINC_Enamine_external_similarity/04_selected_external_ligands_for_docking.csv')
display(selected.head(20))
print('Selected:', len(selected))

from google.colab import files
files.download('ZINC_Enamine_external_similarity.zip')

!pip -q install rdkit pandas numpy tqdm openpyxl matplotlib

!python 32_merge_ZINC_Enamine_PubChem_seed_files_for_JAK2.py \
  --input_dir . \
  --outdir JAK2_external_merged \
  --select_total 150

!python 32_merge_ZINC_Enamine_PubChem_seed_files_for_JAK2.py \
  --input_dir . \
  --outdir JAK2_external_merged_strict \
  --select_total 100 \
  --strict_druglike

import pandas as pd, os, glob

print("Output files:")
for f in glob.glob("JAK2_external_merged/*"):
    print(f)

selected = pd.read_csv("JAK2_external_merged/04_selected_external_ligands_for_docking.csv")
display(selected.head(20))
print("Selected molecules:", len(selected))

import shutil
from google.colab import files
import os

output_folder = "JAK2_external_merged"

zip_file = shutil.make_archive(
    base_name=output_folder + "_outputs",
    format="zip",
    root_dir=output_folder
)

print("Created:", zip_file)
print("Size MB:", round(os.path.getsize(zip_file) / (1024 * 1024), 2))

files.download(zip_file)